### ISSUE TITLE
Double requests (ENTER + EXIT) on fence exit

### ISSUE THREAD

**Issue by bluewalk** [LocativeHQ/Locative-iOS#52] opened 2016-09-20 09:43 UTC
Since the last Locative update it sends an ENTER and EXIT request to my API upon exiting a fence. Upon entering it only sends an ENTER request (so that's fine).

Looks like this is unwanted behavior of course

![photo-2016-09-21-07-20-48_2049](https://cloud.githubusercontent.com/assets/6522477/18698847/a3a7145c-7fcd-11e6-952c-5a3db1fd98ab.PNG)

**Comment by kimar** [comment] 2016-09-25 21:34
I've also seen this a hand full of times but it's not 100% reproducible to me. Any help appreciated on this, we might just simply want to implement a (configurable) threshold, there's a chance of certain flakeyness (e.g. cell tower changes etc.) which might actually negatively influence this bug. (Geofencing heavily relies on triangulation via cell and wifi).

**Comment by kimar** [comment] 2016-09-25 21:35
Also since the last update it's feasible to receive fencelogs without having a server configured, this is expected behaviour but will need to be taken into account with this. There might be a slight chance this also affects the behaviour: https://github.com/LocativeHQ/Locative-iOS/blob/master/Locative/Lib/GeofenceManager.m#L135

**Comment by adgoudsmit** [comment] 2016-09-26 07:12
As a note from my side, i have this situation als on entering a geofence. Not always but sometimes. And when it sends multiple (sometimes even 3) it can happen the last being sent is an "entry" event.

**Comment by kimar** [comment] 2016-10-03 05:47
I might have found the issue, the method which should perform a cleanup of registered geofenecs hasn't been invoked correctly. This might have lead to Geofences getting registered multiple times which might have lead to the behaviour described. A fix will be deployed in `v2.1.1`. https://github.com/LocativeHQ/Locative-iOS/commit/a089220e97144d5f5be18195ed8a2dc5a5e71879#diff-df755a2a87d3da0a13ea29e85a76a837L173

**Comment by bluewalk** [comment] 2016-10-04 14:32
Just installed the update, still have multiple entry evets (entry, exit and then entry again). Will continue to followup

**Comment by kimar** [comment] 2016-10-04 19:52
Did you open the app? Cleanup is performed once the app has been opened. Thx for trying.

**Comment by charlescsparrow** [comment] 2016-10-05 00:14
For me, just updating, opening the app after updating, nor recreating the fence after updating seemed to work. But I then deleted the app entirely and recreated the fence and just got a single entry event arriving home. Will keep testing but hopefully the update and clean install worked!  Thanks for the update!

**Comment by bluewalk** [comment] 2016-10-05 05:51
I have opened the app now after updating and it seems that the fences are now nicely processed once. I'll keep an eye on it but so far so good :)

**Comment by bluewalk** [comment] 2016-10-07 05:12
Unfortunately It registered double events this morning when I left home:
![fences](https://cloud.githubusercontent.com/assets/6522477/19179411/43ed92e2-8c5d-11e6-978a-7fbe015eb7a7.PNG)

**Comment by kimar** [comment] 2016-10-07 05:29
@bluewalk I see, reopening this not sure if @charlescsparrow 's solution worked

**Comment by kimar** [comment] 2016-10-07 05:30
Will continue investigating, haven't seen duplicate events recently.

**Comment by charlescsparrow** [comment] 2016-10-11 02:04
Unfortunately no luck for me, sorry for the delay in reporting back. The uninstall and reinstall seems to only work for the first entry or exit, then the dups start back. This morning leaving for work produced 3 sets of home then away events then closed with a single home event, which would have left the house in "home" mode despite being away.

**Comment by thethereza** [comment] 2016-10-12 15:55
Ditto on getting multiple events. Is there a way to enable debugging to see what the OS sees (in terms of setup fences)

**Comment by charlescsparrow** [comment] 2016-10-20 01:04
Still hoping for a fix here. Thanks!

**Comment by kimar** [comment] 2016-10-20 01:16
@charlescsparrow @thethereza I'll come up with a way to debug things here, can't reproduce this consistently and it's a PITA to debug by the means of what  gives us. I'll see if I can have a look into this tonight.

**Comment by thethereza** [comment] 2016-10-20 01:21
@kimar  It's gotten silly.  I got 16 enter/exit notices back to back when i got home yesterday.  I just deleted and reinstalled the app and now it didn't work once and i got two responses the second time.  I'm happy to help debug if there is some way (can I compile using free tools and test on my phone without a developer license?)

**Comment by kimar** [comment] 2016-10-20 09:50
@thethereza @charlescsparrow please join the conversation here: https://gitter.im/LocativeHQ/Locative-iOS

@thethereza yeah you just need to download Xcode from the App Store and grab a free Developer account / Apple ID, here's some further info on how to provision your own device then. No payed account necessary at that time: https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppDistributionGuide/LaunchingYourApponDevices/LaunchingYourApponDevices.html

**Comment by bluewalk** [comment] 2016-10-25 08:48
I've had good hopes with the last update, for two whole days it only reported one entry and one exit event. But this morning i got both in one second :(

**Comment by Aerics** [comment] 2016-11-30 17:11
I`m using the last IOS app with my iPhone 7S and IOS 10.
I have exactly the same problem. Mostly the app trigger two times, sometimes 4 and more. Problem for me is, that i control my heating with fhem and sometimes i`m leaving and the last trigger is home. So my heating works all day :(. So it`s important for me, that i can count on it.

Can i help something to fix this problem?

**Comment by kimar** [comment] 2016-12-18 11:17
Fixed in v3.1.2, added more resilience, successfully confirmed this works in https://github.com/LocativeHQ/Locative-iOS/commit/544dbb4a12d63c63dd1d623af9751a38cfc698b0, built pushed to the App Store for review.

**Closed by kimar** 2016-12-18 11:17 UTC
Labels: bug, hacktoberfest, help wanted
